<div class="product-social">
    <!-- AddThis Button BEGIN -->
    <div class="addthis_toolbox addthis_default_style ">
        <a class="addthis_button_facebook_like at300b" fb:like:layout="button_count">
            <div class="fb-like fb_iframe_widget" data-ref=".VQpBAnK00W8.like" data-layout="button_count" data-show_faces="false" data-action="like" data-width="90" data-font="arial" data-href="http://www.plazathemes.com/demo/ma_sagitta/index.php/shirts/voluptas-nulla.html?___SID=U" data-send="false" fb-xfbml-state="rendered" fb-iframe-plugin-query="action=like&amp;app_id=172525162793917&amp;container_width=0&amp;font=arial&amp;href=http%3A%2F%2Fwww.plazathemes.com%2Fdemo%2Fma_sagitta%2Findex.php%2Fshirts%2Fvoluptas-nulla.html%3F___SID%3DU&amp;layout=button_count&amp;locale=en_US&amp;ref=.VQpBAnK00W8.like&amp;sdk=joey&amp;send=false&amp;show_faces=false&amp;width=90"><span style="vertical-align: bottom; width: 76px; height: 20px;"><iframe name="f37abd7ab8" width="90px" height="1000px" frameborder="0" allowtransparency="true" scrolling="no" title="fb:like Facebook Social Plugin" src="http://www.facebook.com/plugins/like.php?action=like&amp;app_id=172525162793917&amp;channel=http%3A%2F%2Fstatic.ak.facebook.com%2Fconnect%2Fxd_arbiter%2F6Dg4oLkBbYq.js%3Fversion%3D41%23cb%3Df10bd775e%26domain%3Dwww.plazathemes.com%26origin%3Dhttp%253A%252F%252Fwww.plazathemes.com%252Ff3c2fcbad4%26relation%3Dparent.parent&amp;container_width=0&amp;font=arial&amp;href=http%3A%2F%2Fwww.plazathemes.com%2Fdemo%2Fma_sagitta%2Findex.php%2Fshirts%2Fvoluptas-nulla.html%3F___SID%3DU&amp;layout=button_count&amp;locale=en_US&amp;ref=.VQpBAnK00W8.like&amp;sdk=joey&amp;send=false&amp;show_faces=false&amp;width=90" style="border: none; visibility: visible; width: 76px; height: 20px;" class=""></iframe></span>
            </div>
        </a>
        <a class="addthis_button_tweet at300b">
            <iframe id="twitter-widget-0" scrolling="no" frameborder="0" allowtransparency="true" src="http://platform.twitter.com/widgets/tweet_button.3b6d1172463333ba9e3a4714e5a08ce6.en.html#_=1426735364781&amp;count=horizontal&amp;counturl=http%3A%2F%2Fwww.plazathemes.com%2Fdemo%2Fma_sagitta%2Findex.php%2Fshirts%2Fvoluptas-nulla.html%3F___SID%3DU&amp;dnt=true&amp;id=twitter-widget-0&amp;lang=en&amp;original_referer=http%3A%2F%2Fwww.plazathemes.com%2Fdemo%2Fma_sagitta%2Findex.php%2Fshirts%2Fvoluptas-nulla.html%3F___SID%3DU&amp;size=m&amp;text=Voluptas%20nulla%20-%20Shirts%3A&amp;url=http%3A%2F%2Fwww.plazathemes.com%2Fdemo%2Fma_sagitta%2Findex.php%2Fshirts%2Fvoluptas-nulla.html%3F___SID%3DU%23.VQpBArkkfNQ.twitter" class="twitter-share-button twitter-tweet-button twitter-share-button twitter-count-horizontal" title="Twitter Tweet Button" data-twttr-rendered="true" style="width: 120px; height: 20px;"></iframe>
        </a>
        <a class="addthis_button_google_plusone at300b" g:plusone:size="medium">
            <div id="___plusone_0" style="text-indent: 0px; margin: 0px; padding: 0px; border-style: none; float: none; line-height: normal; font-size: 1px; vertical-align: baseline; display: inline-block; width: 90px; height: 20px; background: transparent;">
                <iframe frameborder="0" hspace="0" marginheight="0" marginwidth="0" scrolling="no" style="position: static; top: 0px; width: 90px; margin: 0px; border-style: none; left: 0px; visibility: visible; height: 20px;" tabindex="0" vspace="0" width="100%" id="I0_1426735364971" name="I0_1426735364971" src="https://apis.google.com/u/0/se/0/_/+1/fastbutton?usegapi=1&amp;size=medium&amp;hl=en-US&amp;origin=http%3A%2F%2Fwww.plazathemes.com&amp;url=http%3A%2F%2Fwww.plazathemes.com%2Fdemo%2Fma_sagitta%2Findex.php%2Fshirts%2Fvoluptas-nulla.html%3F___SID%3DU&amp;gsrc=3p&amp;ic=1&amp;jsh=m%3B%2F_%2Fscs%2Fapps-static%2F_%2Fjs%2Fk%3Doz.gapi.vi.04LAw0ZKHPs.O%2Fm%3D__features__%2Fam%3DIQ%2Frt%3Dj%2Fd%3D1%2Ft%3Dzcms%2Frs%3DAGLTcCMA8vIXizTKzDONmDyIHpKr4EXigw#_methods=onPlusOne%2C_ready%2C_close%2C_open%2C_resizeMe%2C_renderstart%2Concircled%2Cdrefresh%2Cerefresh&amp;id=I0_1426735364971&amp;parent=http%3A%2F%2Fwww.plazathemes.com&amp;pfname=&amp;rpctoken=12926918" data-gapiattached="true" title="+1"></iframe>
            </div>
        </a>
        <div class="atclear"></div>
    </div>
</div>